/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package me.minecraft.plugin

import org.bukkit.plugin.java.JavaPlugin

public class Main : JavaPlugin() {

    public override fun onEnable() {
        logger.info("Hello, this is plugin!");
        server.pluginManager.registerEvents(MainEvent(), this);
    }

    public override fun onDisable() {
        logger.info("Out!");
    }
}