/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package KotlinTest

import org.bukkit.plugin.java.JavaPlugin

public class Main : JavaPlugin() {

    public override fun onEnable() {
        getLogger().info("Hello, this is plugin!");
        getServer().getPluginManager().registerEvents(MainEvent(), this);
    }

    public override fun onDisable() {
        getLogger().info("Out!");
    }
}